name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main #Trigger workflor on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: checout the repository 
      - name: Checkout code
        uses: actions/checkout@v3

    # Step 2: Set up AWS credentials
      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and tag Docker image
        run: |
          docker build --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} -t 778425189746.dkr.ecr.us-east-1.amazonaws.com/hola-mundo-repo:back_latest .
   
      - name: Push Docker image to ECR
        run: |
          docker push 778425189746.dkr.ecr.us-east-1.amazonaws.com/hola-mundo-repo:back_latest

      # Step 5: SSH into EC2 and Redeploy Container
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull 778425189746.dkr.ecr.us-east-1.amazonaws.com/hola-mundo-repo:back_latest
            docker stop JavaBackend || true
            docker rm JavaBackend || true
            docker system prune -a --volumes -f
            docker run -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} -d --name JavaBackend -p 8080:8080 --memory=1g 778425189746.dkr.ecr.us-east-1.amazonaws.com/hola-mundo-repo:back_latest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST_2 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull 778425189746.dkr.ecr.us-east-1.amazonaws.com/hola-mundo-repo:back_latest
            docker stop JavaBackend || true
            docker rm JavaBackend || true
            docker system prune -a --volumes -f 
            docker run -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} -d --name JavaBackend -p 8080:8080 --memory=1g 778425189746.dkr.ecr.us-east-1.amazonaws.com/hola-mundo-repo:back_latest


